name: progear_smart_bag
description: A smart bag flutter application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mesh: ^0.5.0

  google_fonts: ^6.1.0
  supabase_flutter: ^2.10.1
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.0
  # blue bluetooth
  flutter_blue_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
